"""Generate a markdown draft of the report's data sections from the registry.

Reads `experiments/registry.csv` plus the per-run `experiments/runs/*.json`
files and emits `experiments/analysis/report_sections.md` with:

    - Methodology table per `model_type` (configs)
    - Dev set results table (F1, EM, SQL_EM, error rate per run)
    - Best run per track summary
    - Task 1 ablation tables (T5 ft variants)
    - Task 3 ablation tables (Gemma k sweep, selection comparison, schema on/off)
    - Best LLM prompt (system instruction + selection / schema settings)

The output is markdown the user pastes into the Overleaf template.

This script is read-only — never modifies registry / results / records.

CLI:

    python tools/report_draft.py
    python tools/report_draft.py --output experiments/analysis/report_sections.md
"""
import argparse
import csv
import json
import os
import sys
from collections import defaultdict
from typing import Dict, List, Optional

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..'))
REGISTRY_PATH = os.path.join(ROOT, 'experiments', 'registry.csv')
RUNS_DIR = os.path.join(ROOT, 'experiments', 'runs')
ANALYSIS_DIR = os.path.join(ROOT, 'experiments', 'analysis')


def fnum(x, dp: int = 4) -> str:
    if x is None or x == '' or x == 'None':
        return '—'
    try:
        return f'{float(x):.{dp}f}'
    except (ValueError, TypeError):
        return '—'


def fpct(x, dp: int = 1) -> str:
    if x is None or x == '' or x == 'None':
        return '—'
    try:
        return f'{100.0 * float(x):.{dp}f}%'
    except (ValueError, TypeError):
        return '—'


def load_registry() -> List[Dict[str, str]]:
    if not os.path.exists(REGISTRY_PATH):
        return []
    with open(REGISTRY_PATH, 'r', encoding='utf-8') as f:
        return list(csv.DictReader(f))


def load_run_json(run_id: str) -> Optional[dict]:
    p = os.path.join(RUNS_DIR, f'{run_id}.json')
    if not os.path.exists(p):
        return None
    try:
        with open(p, 'r', encoding='utf-8') as f:
            return json.load(f)
    except Exception:
        return None


def parse_config(row: Dict[str, str]) -> dict:
    raw = row.get('config_json', '') or '{}'
    try:
        return json.loads(raw)
    except Exception:
        return {}


def best_per_type(rows: List[Dict[str, str]], metric: str = 'dev_record_f1') -> Dict[str, Dict]:
    out: Dict[str, Dict] = {}
    for r in rows:
        try:
            f1 = float(r.get(metric) or 'nan')
        except (ValueError, TypeError):
            continue
        if f1 != f1:  # NaN
            continue
        mt = r.get('model_type', 'unknown')
        if mt not in out or f1 > float(out[mt][metric] or 0):
            out[mt] = r
    return out


# ---------------- section renderers ---------------- #

def render_header() -> List[str]:
    out = [
        '# A4 — auto-generated report sections',
        '',
        'This file is generated by `tools/report_draft.py` from `experiments/registry.csv`.',
        'Paste the relevant tables into the Overleaf report template; do not edit this file by hand.',
        '',
        '> Replace **NAME / NETID / GITHUB_URL** at the top of the Overleaf PDF, then drop in the tables below.',
        '',
    ]
    return out


def render_methodology(rows: List[Dict[str, str]]) -> List[str]:
    out = ['## Methodology', '']
    by_type: Dict[str, List[Dict]] = defaultdict(list)
    for r in rows:
        by_type[r.get('model_type', 'unknown')].append(r)

    for mt in sorted(by_type):
        out.append(f'### `{mt}`')
        out.append('')
        out.append('| Run | LR | Epochs | Effective batch | Schedule | Label smoothing | Other |')
        out.append('|---|---:|---:|---:|---|---:|---|')
        for r in by_type[mt]:
            cfg = parse_config(r)
            eff_bs = cfg.get('batch_size', '?')
            ga = cfg.get('grad_accumulation_steps', 1)
            try:
                eff_bs_str = f'{int(eff_bs) * int(ga)}'
            except Exception:
                eff_bs_str = f'{eff_bs}×{ga}'
            schedule = cfg.get('lr_schedule', '?')
            warmup = cfg.get('warmup_steps', '?')
            ls = cfg.get('label_smoothing', 0)
            other_bits = []
            if cfg.get('freeze_encoder'):
                other_bits.append('frozen encoder')
            if cfg.get('use_amp') is False:
                other_bits.append('fp32')
            if cfg.get('gradient_checkpointing'):
                other_bits.append('grad ckpt')
            if cfg.get('num_beams') and int(cfg.get('num_beams', 1)) > 1:
                other_bits.append(f"beam={cfg.get('num_beams')}")
            if cfg.get('k') is not None:
                other_bits.append(f"k={cfg.get('k')}")
            if cfg.get('example_selection'):
                other_bits.append(f"sel={cfg.get('example_selection')}")
            if cfg.get('include_schema') is not None:
                other_bits.append(f"schema={cfg.get('include_schema')}")
            other = ', '.join(other_bits) if other_bits else '—'
            out.append(
                f"| {r['experiment_name']} | {cfg.get('lr', '—')} | "
                f"{cfg.get('max_epochs', '—')} | {eff_bs_str} | "
                f"{schedule} (warmup {warmup}) | {ls} | {other} |"
            )
        out.append('')
    return out


def render_dev_table(rows: List[Dict[str, str]]) -> List[str]:
    out = ['## Dev set results — every run', '']
    out.append('| `model_type` | run | Record F1 | Record EM | SQL EM | Error rate | Epochs | Duration (s) |')
    out.append('|---|---|---:|---:|---:|---:|---:|---:|')
    for r in rows:
        out.append(
            f"| {r['model_type']} | {r['experiment_name']} | "
            f"{fnum(r.get('dev_record_f1'))} | "
            f"{fnum(r.get('dev_record_em'))} | "
            f"{fnum(r.get('dev_sql_em'))} | "
            f"{fpct(r.get('dev_error_rate'))} | "
            f"{r.get('epochs_trained', '—')} | "
            f"{fnum(r.get('duration_sec'), dp=0)} |"
        )
    out.append('')
    return out


def render_best_per_track(rows: List[Dict[str, str]]) -> List[str]:
    best = best_per_type(rows, metric='dev_record_f1')
    out = ['## Best run per track (dev F1)', '']
    out.append('| Track | Best experiment | Dev F1 | Dev EM | SQL EM | Err rate |')
    out.append('|---|---|---:|---:|---:|---:|')
    for mt in sorted(best):
        r = best[mt]
        out.append(
            f"| {mt} | {r['experiment_name']} | "
            f"{fnum(r.get('dev_record_f1'))} | "
            f"{fnum(r.get('dev_record_em'))} | "
            f"{fnum(r.get('dev_sql_em'))} | "
            f"{fpct(r.get('dev_error_rate'))} |"
        )
    out.append('')
    return out


def render_t5_ft_ablation(rows: List[Dict[str, str]]) -> List[str]:
    t5_ft = [r for r in rows if r.get('model_type') == 't5_ft']
    if not t5_ft:
        return ['## Task 1 ablation (T5 finetune)\n', '_no rows yet_\n']
    out = ['## Task 1 ablation (T5 finetune)', '']
    out.append('| Variant | Decoding | Frozen encoder | Dev F1 | Dev EM | Err rate |')
    out.append('|---|---|---|---:|---:|---:|')
    for r in t5_ft:
        cfg = parse_config(r)
        decoding = f"beam={cfg.get('num_beams', 1)}" if int(cfg.get('num_beams', 1)) > 1 else 'greedy'
        out.append(
            f"| {r['experiment_name']} | {decoding} | "
            f"{cfg.get('freeze_encoder', False)} | "
            f"{fnum(r.get('dev_record_f1'))} | "
            f"{fnum(r.get('dev_record_em'))} | "
            f"{fpct(r.get('dev_error_rate'))} |"
        )
    out.append('')
    return out


def render_gemma_ablation(rows: List[Dict[str, str]]) -> List[str]:
    gemma = [r for r in rows if r.get('model_type', '').startswith('gemma_1b')]
    if not gemma:
        return ['## Task 3 ablation (Gemma-1B)\n', '_no rows yet_\n']
    out = ['## Task 3 ablation (Gemma-1B)', '']
    out.append('| Variant | k | Selection | Schema | Dev F1 | Dev EM | Err rate |')
    out.append('|---|---:|---|---|---:|---:|---:|')
    for r in gemma:
        cfg = parse_config(r)
        out.append(
            f"| {r['experiment_name']} | {cfg.get('k', '?')} | "
            f"{cfg.get('example_selection', '—')} | "
            f"{cfg.get('include_schema', False)} | "
            f"{fnum(r.get('dev_record_f1'))} | "
            f"{fnum(r.get('dev_record_em'))} | "
            f"{fpct(r.get('dev_error_rate'))} |"
        )
    out.append('')

    # Pair-comparison subtables (only if pairs exist)
    pairs = {
        'k=3 random vs BM25 (selection method)': [
            'gemma1b_k3_random', 'gemma1b_k3_bm25',
        ],
        'k=3 BM25 — schema on vs off (prompt component)': [
            'gemma1b_k3_bm25', 'gemma1b_k3_bm25_schema',
        ],
    }
    by_name = {r['experiment_name']: r for r in gemma}
    for title, names in pairs.items():
        present = [n for n in names if n in by_name]
        if len(present) < 2:
            continue
        out.append(f'### {title}')
        out.append('')
        out.append('| Variant | Dev F1 | Δ vs left |')
        out.append('|---|---:|---:|')
        base_f1 = float(by_name[present[0]].get('dev_record_f1') or 0.0)
        for n in present:
            r = by_name[n]
            f1 = float(r.get('dev_record_f1') or 0.0)
            delta = '—' if n == present[0] else f'{f1 - base_f1:+.4f}'
            out.append(f'| {n} | {fnum(f1)} | {delta} |')
        out.append('')
    return out


def render_best_prompt(rows: List[Dict[str, str]]) -> List[str]:
    llm = [r for r in rows if r.get('model_type', '').startswith(('codegemma_', 'gemma_'))]
    if not llm:
        return ['## Best LLM prompt\n', '_no LLM runs yet_\n']
    best = max(llm, key=lambda r: float(r.get('dev_record_f1') or 0.0))
    cfg = parse_config(best)
    run_json = load_run_json(best['run_id']) or {}
    cfg_json = run_json.get('config', cfg)

    out = ['## Best LLM prompt', '',
           f"- Best LLM run: **{best['experiment_name']}** "
           f"(dev F1 = {fnum(best.get('dev_record_f1'))})",
           f"- Model: `{cfg_json.get('model_name')}`",
           f"- k = {cfg_json.get('k')}, selection = `{cfg_json.get('example_selection')}`, "
           f"schema = {cfg_json.get('include_schema')}",
           '']
    sys_inst = cfg_json.get('system_instruction')
    if not sys_inst:
        sys_inst = ('(default system prompt — see DEFAULT_SYSTEM in '
                    '`prompting_harness.py`)')
    out.append('### System instruction')
    out.append('')
    out.append('```')
    out.append(str(sys_inst).strip())
    out.append('```')
    out.append('')
    out.append('### User-turn template (per query)')
    out.append('')
    out.append('Built by `prompting_harness.build_prompt(query, examples, schema)`. '
               'Schematically:')
    out.append('')
    out.append('```')
    out.append('Database schema:')
    out.append('<contents of data/flight_database.schema>')
    out.append('')
    out.append('Examples:')
    out.append('NL: <retrieved by BM25>')
    out.append('SQL: <gold SQL>')
    out.append('... (k examples)')
    out.append('')
    out.append('Now write the SQLite SQL query for the following instruction.')
    out.append('NL: <input>')
    out.append('SQL:')
    out.append('```')
    out.append('')
    return out


def render_error_analysis_index() -> List[str]:
    out = ['## Error analysis (per system)', '']
    if not os.path.isdir(ANALYSIS_DIR):
        out.append('_no analysis files yet — run `python tools/error_analysis.py --all`_')
        out.append('')
        return out
    files = sorted(
        f for f in os.listdir(ANALYSIS_DIR)
        if f.startswith('error_categories_') and f.endswith('.md')
    )
    if not files:
        out.append('_no analysis files yet — run `python tools/error_analysis.py --all`_')
    else:
        out.append('Per-run error tables in `experiments/analysis/`:')
        out.append('')
        for f in files:
            out.append(f'- [{f}]({f})')
    out.append('')
    return out


def render() -> str:
    rows = load_registry()
    out: List[str] = []
    out += render_header()
    if not rows:
        out += ['_registry is empty — train at least one run before regenerating._']
        return '\n'.join(out)
    out += render_methodology(rows)
    out += render_dev_table(rows)
    out += render_best_per_track(rows)
    out += render_t5_ft_ablation(rows)
    out += render_gemma_ablation(rows)
    out += render_best_prompt(rows)
    out += render_error_analysis_index()
    return '\n'.join(out)


def main() -> None:
    p = argparse.ArgumentParser()
    p.add_argument('--output',
                   default=os.path.join(ANALYSIS_DIR, 'report_sections.md'))
    args = p.parse_args()
    os.makedirs(os.path.dirname(args.output), exist_ok=True)
    text = render()
    with open(args.output, 'w', encoding='utf-8') as f:
        f.write(text)
    print(f'wrote {args.output}  ({len(text):,} chars, {text.count(chr(10)) + 1} lines)')


if __name__ == '__main__':
    main()
